### ISSUE TITLE
Deprecated matplotlib function

### ISSUE THREAD

**Issue by ikeurquhart** [behrouzz/hypatie#2]
Traceback (most recent call last):
  File "/Users/ikeurquhart/python/hypatie/ike.py", line 3, in <module>
    fig, ax = star_chart(lon=2.2945, lat=48.8584)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikeurquhart/python/hypatie/hypatie/plots.py", line 183, in star_chart
    fig, ax = plot_altaz(az, alt, mag=mag)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikeurquhart/python/hypatie/hypatie/plots.py", line 109, in plot_altaz
    ax.set_rlim(90, 0, 1)
TypeError: PolarAxes.set_rlim() takes from 1 to 3 positional arguments but 4 were given

Changing the line to ax.set_rlim(90, 0) seemed to solve it.

**Comment by ikeurquhart** [comment]
@behrouzz

**Comment by ikeurquhart** [comment]
Sweet package btw
